name: cryptocurrencytruckerapp
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: '^3.8.1'  

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
